config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  root 'home#index'
  resources :registrations, only: %i[new create]
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone_number, presence: true
  validates :password, presence: true, length: { minimum: 8 }

  after_create :send_notification

  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def send_notification
    # Logic to send notification using SMS API
    SmsNotificationJob.perform_later(id)
  end

  public :send_notification unless Rails.env.production?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # Successful signup, you can redirect to a different page or do something else
      redirect_to root_path, notice: 'User successfully created!'
    else
      # Signup failed, render the signup form again with error messages
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone_number, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="container">
  <h1>Welcome to Notification Trigger App</h1>
  <p>To SignUp and Trigger notificaion Click on below link. Notification will trigger after successfully signUp.</p>
  <%= link_to 'Sign Up', new_registration_path, class: 'signup-link' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotificationTriggerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li class ="error_message"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>

 <div class=”alert alert-info mt-4″>

   <%= flash[:notice] %>

 </div>

<% end %>

<% if flash[:alert] %>

 <div class=”alert alert-warning mt-4″>

   <%= flash[:alert] %>

 </div>

<% end %>